databaseUrl=${MONGO_URI:mongodb://mongo:27017}
databaseName=${MONGO_DB_NAME:ead_ca2}
databaseCollection=${MONGO_COLLECTION:ead_2024}

management.endpoints.web.exposure.include=env,health,info,metrics

logging.level.org.springframework.web=INFO